language: csharp
sudo: required  
dist: trusty  
dotnet: 1.0.0-preview3-004056
env:  
  - DOTNETCORE=1
mono:  
  - none
os:  
  - linux
osx_image: xcode7.3  
branches:  
  only:
    - master
script:  
- ./build.sh